# Generated by Django 4.1.3 on 2022-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('detalles', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('precios', models.IntegerField()),
            ],
        ),
    ]
